---
# module: ansible-etcd-cluster/configure-etcd.yml
# description: Install host setup files

- name: Make a folder for etcd data
  become: true
  file:
    path: /var/lib/etcd
    state: directory
  notify: Restart etcd

- name: Generate hostlist file
  become: true
  template:
    src: "templates/cluster-hosts.yml.j2"
    dest: "{{ install_dir }}/cluster-hosts.yml"
  notify: Restart etcd

- name: Copy startup script
  become: true
  template:
    src: "templates/etcd-launch.py"
    dest: "{{ install_dir }}/etcd-launch.py"
    mode: u=rwx,g=rx,o=gx
  notify: Restart etcd

- name: Copy systemd unit file
  become: true
  template:
    src: "templates/etcd.service"
    dest: "/etc/systemd/system/etcd.service"
  notify: Restart etcd

- name: Make sure systemd is reloaded
  meta: flush_handlers

- name: Enable etcd service on boot
  systemd:
    name: etcd
    enabled: "{{ etcd_start_on_boot }}"
