# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # Use Ubuntu LTS (Xenial/16.04) without SSH key bug
    config.vm.box = "bento/ubuntu-16.04"

    # Disable the new default behavior introduced in Vagrant 1.7, to
    # ensure that all Vagrant machines will use the same SSH key pair.
    # See https://github.com/mitchellh/vagrant/issues/5005
    config.ssh.insert_key = false

    (1..3).each do |i|
        config.vm.define "host-#{i}" do |node|
            node.vm.hostname = "vagrant-etcdkicker-host-#{i}"

            node.vm.network "private_network", ip: "192.168.56.22#{i}"

            node.vm.network :forwarded_port, guest: 22, host: "223#{i}", id: 'ssh'
        end
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo sed -i " 1 s/.*/& $(hostname)/" /etc/hosts
    SHELL

  end
  
